pipeline:
  msa: true
  boltz: true
  esm: true
  es: true
input:
  fasta_dir: /n/home06/tbush/gfp_function_prediction/data/trial_10
output:
  parent_dir: /n/holylfs06/LABS/bsabatini_lab/Everyone/protforge/test_10
msa:
  max_files_per_job: 25
  array_max_concurrency: 10
  mmseq2_db: /n/holylfs06/LABS/kempner_shared/Everyone/workflow/boltz/mmseq2_db
  colabfold_db: /n/holylfs06/LABS/kempner_shared/Everyone/workflow/boltz/colabfold_db
  colabfold_bin: /n/holylfs06/LABS/kempner_shared/Everyone/common_envs/miniconda3/envs/boltz/localcolabfold/colabfold-conda/bin
boltz:
  max_files_per_job: 25
  array_max_concurrency: 10
  delete_msa_after_processing: false
  recycling_steps: 10
  diffusion_samples: 25
  num_runs: 1
  cache_dir: /n/holylfs06/LABS/kempner_shared/Everyone/workflow/boltz/boltz_db
  colabfold_db: /n/holylfs06/LABS/kempner_shared/Everyone/workflow/boltz/colabfold_db
  env_path: /n/holylfs06/LABS/kempner_shared/Everyone/common_envs/miniconda3/envs/boltz
esm:
  num_chunks: 1
  array_max_concurrency: 20
  env_path: /n/holylfs06/LABS/bsabatini_lab/Everyone/protforge/envs/esm
  cache_dir: /n/holylfs06/LABS/bsabatini_lab/Everyone/esm_models_cache
es:
  pdanalysis_dir: /n/holylfs06/LABS/bsabatini_lab/Everyone/protforge/PDAnalysis
  ref_dir: /n/netscratch/kempner_bsabatini_lab/Lab/Boltz-project/original_structures/sequences/test_input_10/boltz
  ref_path: ''
  ref_seq: ''
  method:
  - strain
  min_plddt: 70
  lddt_cutoffs:
  - 0.125
  - 0.25
  - 0.5
  - 1.0
  env_path: /n/holylfs06/LABS/bsabatini_lab/Everyone/protforge/envs/es-analysis
slurm:
  log_dir: /n/home06/tbush/job_logs
  partition: kempner_h100
  account: kempner_bsabatini_lab
  email: thomasbush52@gmail.com
  esm:
    partition: kempner
  es:
    partition: kempner
  msa:
    partition: kempner
