pipeline:
  msa: true
  boltz: true
  esmc: true
  esmfold: true
  openfold: true
input:
  fasta_dir: /n/home06/tbush/trial_10
output:
  parent_dir: /n/holylfs06/LABS/bsabatini_lab/Everyone/tbush/test_protforge/outputs
msa:
  max_files_per_job: 50
  array_max_concurrency: 10
  mmseq2_db: /n/holylfs06/LABS/kempner_shared/Everyone/workflow/boltz/mmseq2_db
  colabfold_db: /n/holylfs06/LABS/kempner_shared/Everyone/workflow/boltz/colabfold_db
boltz:
  max_files_per_job: 22
  array_max_concurrency: 10
  delete_msa_after_processing: false
  recycling_steps: 10
  diffusion_samples: 25
  samples_to_save: 1
  num_runs: 1
  cache_dir: /n/holylfs06/LABS/kempner_shared/Everyone/workflow/boltz/boltz_db
  colabfold_db: /n/holylfs06/LABS/kempner_shared/Everyone/workflow/boltz/colabfold_db
esmc:
  models:
  - 600M
  max_files_per_job: 30
  chunks_per_group: 1
  cache_dir: /n/holylfs06/LABS/bsabatini_lab/Everyone/tbush/singularity_dev/images/cache_models
  sae:
    enabled: false
    sae_type: all-layers
    layers: all
    max_files_per_job: 25
    chunks_per_group: 1
openfold:
  num_batches: null
  max_files_per_job: 25
  gpus_per_job: 1
  num_workers: 10
  num_diffusion_samples: 5
  num_model_seeds: 1
  samples_to_save: 1
  structure_format: cif
  write_full_confidence: true
  cache_dir: /n/holylfs06/LABS/bsabatini_lab/Everyone/tbush/singularity_dev/images/cache_models
esmfold:
  max_files_per_job: 200
  chunks_per_group: 1
  compile: false
  cache_dir: /n/holylfs06/LABS/bsabatini_lab/Everyone/tbush/singularity_dev/images/cache_models
  num_loops: 3
  num_sampling_steps: 50
  seed: 0
containers:
  runtime: singularity
  gpu: ''
  colabfold: /n/holylfs06/LABS/bsabatini_lab/Everyone/tbush/singularity_dev/images/msa.sif
  boltz: /n/holylfs06/LABS/bsabatini_lab/Everyone/tbush/singularity_dev/images/boltz.sif
  esmc: /n/holylfs06/LABS/bsabatini_lab/Everyone/tbush/singularity_dev/images/fast_esmfold.sif
  esmfold: /n/holylfs06/LABS/bsabatini_lab/Everyone/tbush/singularity_dev/images/fast_esmfold.sif
  openfold: /n/holylfs06/LABS/bsabatini_lab/Everyone/tbush/singularity_dev/images/openfold3.sif
slurm:
  log_dir: /n/holylfs06/LABS/bsabatini_lab/Everyone/tbush/test_protforge/job_logs
  partition: kempner_h100
  account: kempner_bsabatini_lab
  email: thomasbush52@gmail.com
  resources:
    msa:
      mem_mb: 332988
      runtime: 48
      cpus_per_task: 4
      gpus: 1
    boltz:
      mem_mb: 10509
      runtime: 65
      cpus_per_task: 8
      gpus: 1
    esmc:
      mem_mb: 80000
      runtime: 30
      cpus_per_task: 16
      gpus: 1
    esmfold:
      mem_mb: 20372
      runtime: 42
      cpus_per_task: 8
      gpus: 1
    openfold:                # set by hand — estimator does not size OpenFold3
      mem_mb: 64000
      runtime: 90
      cpus_per_task: 10
      gpus: 1
  msa:
    partition: kempner_h100
  boltz:
    partition: kempner
  esmc:
    partition: kempner
  esmfold:
    partition: kempner
  openfold:
    partition: kempner_h100
